server:
  port: 8761

logging:
  file:
    name: src/main/resources/script/stage_log.log
    clean-history-on-start: true
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # ⚠ Exposición segura
  endpoint:
    health:
      show-details: always               # Necesario para dashboards
  metrics:
    export:
      prometheus:
        enabled: true                    # ⚠ Activa /actuator/prometheus

eureka:
  client:
    register-with-eureka: false         # Eureka server NO se registra a sí mismo
    fetch-registry: false
  server:
    enable-self-preservation: true
